server:
  port: 8080
#打印dbug
logging:
  level: debug
spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_spring_boot
    username: root
    password: 123456
springfox:
  documentation:
    swagger-ui:
      enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false